### ISSUE TITLE
luarocks install nixio fails

### ISSUE THREAD

**Issue by karlp** [Neopallium/nixio#10]
on a fresh ubuntu 1204 machine, "sudo luarocks install nixio" doesn't work properly.  It installs a broken nixio that doesn't have the fix for https://github.com/Neopallium/nixio/commit/7220cef77d79aa6d72dc2f6f6d2f0ada6a7b8b5a

I don't know where luarocks is fetching it from exactly?

**Comment by Neopallium** [comment]
Fix in release 0.4: `luarocks install Neopallium/nixio`
