### ISSUE TITLE
installing on Debian/jessy fails with compiler warning

### ISSUE THREAD

**Issue by cehteh** [Neopallium/nixio#12]
using gcc (Debian 4.9.0-6) 4.9.0,
luarocks install

gcc  -O2 --std=gnu99 -Wall -Werror -pedantic  -O2 -fPIC -I/usr/include/lua5.1 -fPIC -c -o src/bind.o src/bind.c 
src/bind.c: In function ‘nixio_sock_accept’:
src/bind.c:259:29: error: argument to ‘sizeof’ in ‘memcpy’ call is the same expression as the destination; did you mean to dereference it? [-Werror=sizeof-pointer-memaccess]
  memcpy(clsock, sock, sizeof(clsock));
                             ^
cc1: all warnings being treated as errors
Makefile:59: recipe for target 'src/bind.o' failed

**Comment by karlp** [comment]
any chance you could get around to getting a new version to luarocks please?  I just tried installing from luarocks today and hit this too.

**Comment by paines** [comment]
Same error in 2020 with Ubuntu 20.10 and gcc 10.2.0. Tried to install lumen via luarocks which depends on nixio-0.3-1

**Comment by lePereT** [comment]
In 2021, too. This prevents the installation of lumen from luarocks. Would it be possible to push the fix to LuaRocks?

**Comment by Neopallium** [comment]
Fix in release 0.4: `luarocks install Neopallium/nixio`
Note I can't update the `nixio` in the root of LuaRocks.  Have to use a namespaced package.
