### ISSUE TITLE
Reading from standard input?

### ISSUE THREAD

**Issue by xopxe** [Neopallium/nixio#18]
I have an applications that uses sockets to distribute data read from the standard input. I don't see how I can get a file descriptor for standard files for nixio. (the ones from Lua like io.input() do not work)

**Comment by Neopallium** [comment]
`nixio.stdin` for input (FD 0), `nixio.stdout` for output (FD 1) and `nixio.stderr` for error (FD 2)

**Comment by Neopallium** [comment]
Add to docs: https://neopallium.github.io/nixio/modules/nixio.html#Tables
